module.exports = {
  plugins: {
    "postcss-sorting": {
      order: ["custom-properties", "declarations", "at-rules", "rules"],
      "properties-order": [
        "content",

        "position",
        "top",
        "right",
        "bottom",
        "left",
        "inset",
        "z-index",

        "visibility",
        "display",

        "flex-flow",
        "flex-direction",
        "flex-wrap",

        "flex",
        "flex-grow",
        "flex-shrink",
        "flex-basis",
        "order",

        "grid",
        "grid-template-columns",
        "grid-template-rows",
        "grid-auto-columns",
        "grid-auto-rows",
        "grid-auto-flow",
        "grid-template-areas",
        "grid-column-gap",
        "grid-row-gap",
        "justify-items",
        "place-items",

        "grid-area",
        "grid-column",
        "grid-row",
        "grid-column-start",
        "grid-column-end",
        "grid-row-start",
        "grid-row-end",

        "justify-self",
        "place-self",

        "justify-content",
        "align-items",
        "align-content",
        "gap",
        "row-gap",
        "column-gap",

        "align-self",

        "float",
        "clear",

        "box-sizing",
        "width",
        "min-width",
        "max-width",
        "height",
        "min-height",
        "max-height",
        "margin",
        "margin-top",
        "margin-right",
        "margin-bottom",
        "margin-left",
        "margin-inline",
        "margin-inline-start",
        "margin-inline-end",
        "margin-block",
        "margin-block-start",
        "margin-block-end",

        "border",
        "border-width",
        "border-style",
        "border-color",
        "border-radius",
        "border-top",
        "border-top-width",
        "border-top-style",
        "border-top-color",
        "border-top-left-radius",
        "border-top-right-radius",
        "border-right",
        "border-right-width",
        "border-right-style",
        "border-right-color",
        "border-bottom",
        "border-bottom-width",
        "border-bottom-style",
        "border-bottom-color",
        "border-bottom-right-radius",
        "border-bottom-left-radius",
        "border-left",
        "border-left-width",
        "border-left-style",
        "border-left-color",

        "border-inline",
        "border-inline-start",
        "border-inline-end",
        "border-block",
        "border-block-start",
        "border-block-end",

        "border-inline-width",
        "border-inline-start-width",
        "border-inline-end-width",

        "border-block-width",
        "border-block-start-width",
        "border-block-end-width",

        "border-inline-style",
        "border-inline-start-style",
        "border-inline-end-style",

        "border-block-style",
        "border-block-start-style",
        "border-block-end-style",

        "border-inline-color",
        "border-inline-start-color",
        "border-inline-end-color",

        "border-block-color",
        "border-block-start-color",
        "border-block-end-color",

        "border-start-start-radius",
        "border-start-end-radius",
        "border-end-start-radius",
        "border-end-end-radius",

        "border-image",

        "padding",
        "padding-top",
        "padding-right",
        "padding-bottom",
        "padding-left",
        "padding-inline",
        "padding-inline-start",
        "padding-inline-end",
        "padding-block",
        "padding-block-start",
        "padding-block-end",

        "object-fit",
        "object-position",

        "vertical-align",
        "box-shadow",
        "outline",
        "outline-color",
        "outline-offset",
        "outline-style",
        "outline-width",

        "opacity",

        "overflow",
        "overflow-x",
        "overflow-y",
        "overflow-wrap",
        "overflow-scrolling",
        "clip",

        "color",
        "fill",
        "stroke",

        "font",
        "font-family",
        "src",
        "font-weight",
        "font-size",
        "font-style",
        "font-display",

        "font-smooth",
        "line-height",
        "letter-spacing",

        "direction",
        "writing-mode",
        "text-orientation",
        "text-align",
        "text-justify",
        "text-decoration",
        "text-decoration-color",
        "text-decoration-line",
        "text-decoration-style",
        "text-decoration-thickness",
        "text-decoration-skip-ink",
        "text-underline-offset",
        "text-underline-position",
        "text-transform",
        "text-indent",
        "text-shadow",
        "text-overflow",
        "text-size-adjust",
        "word-spacing",
        "white-spacing",
        "word-wrap",
        "word-break",
        "hyphens",
        "text-rendering",

        "list-style",
        "list-style-image",
        "list-style-position",
        "list-style-type",

        "background",
        "background-color",
        "background-image",
        "background-repeat",
        "background-position",
        "background-size",
        "background-attachment",
        "background-clip",
        "background-origin",
        "background-blend-mode",
        "backdrop-filter",

        "filter",

        "transition",
        "transition-delay",
        "transition-duration",
        "transition-property",
        "transition-timing-function",
        "transform",
        "transform-origin",
        "transform-style",
        "perspective",
        "perspective-origin",
        "backface-visibility",

        "animation",
        "animation-name",
        "animation-delay",
        "animation-direction",
        "animation-fill-mode",
        "animation-iteration-count",
        "animation-play-state",
        "animation-timing-function",

        "caption-side",
        "table-layout",
        "empty-cells",

        "cursor",
        "pointer-events",
        "user-select",

        "touch-action",
        "scroll-behavior",
        "scroll-padding",
        "...",
      ],
    },
  },
};
